-- MySQL Script generated by MySQL Workbench
-- 05/08/16 18:07:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mkombo_university
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mkombo_university
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mkombo_university` DEFAULT CHARACTER SET utf8 ;
USE `mkombo_university` ;

-- -----------------------------------------------------
-- Table `mkombo_university`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`student` (
  `reg_no` VARCHAR(20) NOT NULL,
  `fname` VARCHAR(45) NULL,
  `mname` VARCHAR(45) NULL,
  `sname` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `marital_status` VARCHAR(45) NULL,
  `nationality` VARCHAR(45) NULL,
  `birth_country` VARCHAR(45) NULL,
  `birth_date` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `phone_no` VARCHAR(15) NULL,
  `email_address` VARCHAR(100) NULL,
  `home_place` VARCHAR(100) NULL,
  `admission_status` VARCHAR(15) NULL DEFAULT 'not approved',
  PRIMARY KEY (`reg_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`health_insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`health_insurance` (
  `membership_no` VARCHAR(45) NOT NULL,
  `vote` VARCHAR(15) NULL,
  `address` VARCHAR(45) NULL,
  `issue_date` VARCHAR(15) NULL,
  `reg_no` VARCHAR(20) NULL,
  PRIMARY KEY (`membership_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`sponsor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`sponsor` (
  `sponsor_name` VARCHAR(100) NULL,
  `sponsor_phone` VARCHAR(40) NULL,
  `sponsor_email` VARCHAR(100) NOT NULL,
  `reg_no` VARCHAR(20) NULL,
  PRIMARY KEY (`sponsor_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`parent` (
  `fullname` VARCHAR(100) NULL,
  `phone_no_p` VARCHAR(45) NULL,
  `email_p` VARCHAR(100) NOT NULL,
  `physical_location` VARCHAR(50) NULL,
  `reg_no` VARCHAR(20) NULL,
  PRIMARY KEY (`email_p`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`bank_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`bank_account` (
  `bank_name` VARCHAR(45) NULL,
  `bank_branch` VARCHAR(45) NULL,
  `account_no` VARCHAR(100) NOT NULL,
  `reg_no` VARCHAR(20) NULL,
  PRIMARY KEY (`account_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`academic_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`academic_info` (
  `index_no_olevel` VARCHAR(100) NOT NULL,
  `index_no_alevel` VARCHAR(100) NULL,
  `school_name_olevel` VARCHAR(100) NULL,
  `school_name_alevel` VARCHAR(100) NULL,
  `sc_location_olevel` VARCHAR(100) NULL,
  `sc_location_alevel` VARCHAR(100) NULL,
  `cert_olevel` VARCHAR(45) NULL,
  `cert_alevel` VARCHAR(45) NULL,
  `completion_yr_olevel` VARCHAR(5) NULL,
  `completion_yr_alevel` VARCHAR(5) NULL,
  `subject_taken` VARCHAR(10) NULL,
  `subject_combination` VARCHAR(5) NULL,
  `reg_no` VARCHAR(20) NULL,
  PRIMARY KEY (`index_no_olevel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`lecturer` (
  `fname` VARCHAR(50) NULL,
  `mname` VARCHAR(50) NULL,
  `sname` VARCHAR(50) NULL,
  `module_title` VARCHAR(100) NULL,
  `gender` VARCHAR(15) NULL,
  `marital_status` VARCHAR(20) NULL,
  `email_address` VARCHAR(100) NOT NULL,
  `nationality` VARCHAR(45) NULL,
  `username` VARCHAR(50) NULL,
  `password` VARCHAR(100) NULL,
  `phone_no` VARCHAR(15) NULL,
  PRIMARY KEY (`email_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`modules` (
  `id_module` INT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NULL,
  `module_title` VARCHAR(100) NULL,
  `course` VARCHAR(45) NULL,
  `year` VARCHAR(20) NULL,
  `semister` VARCHAR(20) NULL,
  `credit` INT(4) NULL,
  PRIMARY KEY (`id_module`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`student_marks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`student_marks` (
  `id_student_marks` INT NOT NULL AUTO_INCREMENT,
  `ca` INT(2) NULL,
  `fe` INT(2) NULL,
  `grade` VARCHAR(2) NULL,
  `grade_point` INT(1) NULL,
  `grade_point_x_credit` INT(5) NULL,
  `reg_no` VARCHAR(20) NULL,
  PRIMARY KEY (`id_student_marks`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`gpa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`gpa` (
  `id_gpa` INT NOT NULL AUTO_INCREMENT,
  `gpa` FLOAT NULL,
  `gpa_class` VARCHAR(20) NULL,
  `reg_no` VARCHAR(20) NULL,
  PRIMARY KEY (`id_gpa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`time_table_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`time_table_master` (
  `fname` VARCHAR(60) NULL,
  `mname` VARCHAR(60) NULL,
  `sname` VARCHAR(60) NULL,
  `username` VARCHAR(60) NULL,
  `password` VARCHAR(100) NULL,
  `gender` VARCHAR(7) NULL,
  `email_address` VARCHAR(100) NOT NULL,
  `phone_no` VARCHAR(15) NULL,
  `nationality` VARCHAR(45) NULL,
  `marital_status` VARCHAR(8) NULL,
  PRIMARY KEY (`email_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`time_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`time_table` (
  `id_time_table` INT NOT NULL AUTO_INCREMENT,
  `day` VARCHAR(10) NULL,
  `module` VARCHAR(100) NULL,
  `time` VARCHAR(45) NULL,
  `v_title` VARCHAR(50) NULL,
  `course` VARCHAR(45) NULL,
  `year` VARCHAR(13) NULL,
  `semister` VARCHAR(15) NULL,
  PRIMARY KEY (`id_time_table`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`venue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`venue` (
  `id_venue` INT NOT NULL AUTO_INCREMENT,
  `v_title` VARCHAR(50) NULL,
  PRIMARY KEY (`id_venue`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`admission_officer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`admission_officer` (
  `fname` VARCHAR(60) NULL,
  `mname` VARCHAR(60) NULL,
  `sname` VARCHAR(60) NULL,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `gender` VARCHAR(7) NULL,
  `phone_no` VARCHAR(15) NULL,
  `email_address` VARCHAR(100) NOT NULL,
  `nationality` VARCHAR(45) NULL,
  `marital_status` VARCHAR(8) NULL,
  PRIMARY KEY (`email_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkombo_university`.`examination_officer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkombo_university`.`examination_officer` (
  `fname` VARCHAR(60) NULL,
  `mname` VARCHAR(60) NULL,
  `sname` VARCHAR(60) NULL,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `gender` VARCHAR(7) NULL,
  `phone_no` VARCHAR(15) NULL,
  `email_address` VARCHAR(100) NOT NULL,
  `nationality` VARCHAR(45) NULL,
  `marital_status` VARCHAR(8) NULL,
  PRIMARY KEY (`email_address`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
